FROM ruby:3-slim

RUN apt-get update && apt-get install -y --no-install-recommends vim curl git build-essential libyaml-dev

WORKDIR /src/conjur-api

COPY Gemfile conjur-api.gemspec VERSION ./
COPY lib/conjur-api/version.rb ./lib/conjur-api/

RUN bundle

COPY . ./
